services:
  - type: web
    name: backend-api
    runtime: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
